### ISSUE TITLE
Ready for a release yet?

### ISSUE THREAD

**Issue by liscio** [ReactiveCocoa/ReactiveObjCBridge#15]
I'm going through some of my Cartfiles and noticed that this repo still doesn't have a release tag set yet. Is there anything that we're waiting on before throwing a 1.0.0 on this?

**Comment by mdiep** [comment]
No, I think this is good to go! You can go ahead if you want, otherwise I'll do it when I find a few minutes.

**Comment by mdiep** [comment]
https://github.com/ReactiveCocoa/ReactiveObjCBridge/releases/tag/1.0.

**Comment by liscio** [comment]
@mdiep Looks like you beat me to it, thanks!
