### ISSUE TITLE
`RACsignal.toSignalProducer()` unavailable

### ISSUE THREAD

**Issue by opfeffer** [ReactiveCocoa/ReactiveObjCBridge#22]
The [README.md](https://github.com/ReactiveCocoa/ReactiveObjCBridge#racsignal-and-signalproducer-or-signal) reads:
> “Hot” RACSignals cannot be directly converted into Signals, because any RACSignal subscription could potentially involve side effects. To obtain a Signal, use RACSignal.toSignalProducer followed by SignalProducer.start, which will make those potential side effects explicit.

I have an instance of `RACSignal` due to a mixed-language project. Looking through XCode's auto-completion suggestions, I'm not seeing anything like `toSignalProducer`.

Could I get a code example of how to turn a `RACSignal` back to `Signal`?

Thanks!

**Comment by andersio** [comment]
You can produce a `Signal` from a `SignalProducer` using `startWithSignal`. Note that the subscription side effect would run after the `setUp` closure is invoked, but before `startWithSignal` returns.

```
signal.toSignalProducer.startWithSignal { signal, interrupter in
    // Do your stuff with `signal`.
}
```

**Comment by opfeffer** [comment]
Thanks for getting back to me.

I'm afraid I didn't do a very good job describing my problem - I have an ObjC interface that looks like so:

     @property (nonatomic, strong, readonly) RACSignal<NSDictionary *> *events;

Now, my view/business layer is written in swift mostly and I'm trying to combine `events` with some other Swift-defined `Signal`s. I was able to achieve the reverse, Swift->ObjC with **ReactiveObjCBridge**'s extensions to `SignalProtocol`

     public func toRACSignal() -> RACSignal<Self.Value.Wrapped>

but I'm not sure how I can transform a `RACSignal` to a `Signal`?

In your response, you said `signal.toSignalProducer().startWithSignal { ... }`, but `events.toSignalProducer()` throws compiler warning:

![Compiler](https://cloud.githubusercontent.com/assets/1138127/24657672/25694cf4-1915-11e7-9be4-d82b40c2dd69.png)

What am I missing? Thanks!

**Comment by andersio** [comment]
https://github.com/ReactiveCocoa/ReactiveObjCBridge/blob/master/ReactiveObjCBridge/ObjectiveCBridging.swift#L122

It seems it was replaced by `bridgedSignalProducer(from:)` due to limitations of ObjC generics in Swift.

**Comment by NikKovIos** [comment]
Could you please explain how to properly convert RACSignal to SignalProducer?
I've write something like 
```swift
extension RACSignal {
    func toSignalProducer() -> SignalProducer<ValueType, AnyError> {
        return SignalProducer(self)
    }
}
```
but the compiler warn at it(

**Comment by andersio** [comment]
It should be `ValueType?` since `ValueType` is annotated as nullable for API backwards compatibility.

But AFAIK it still won’t compile — there are plenty of restrictions in Swift regarding Objective-C lightweight generics. At least last when we tried, the compiler rejects any extension referring to any generic parameter.

**Comment by NikKovIos** [comment]
Yes, so i manually wrap every rac_..  to SignalProducer (
