### ISSUE TITLE
'ActionProtocol' is deprecated: This protocol is no longer necessary and will be removed in a future version of ReactiveSwift. Use Action directly instead.

### ISSUE THREAD

**Issue by mauh-akra** [ReactiveCocoa/ReactiveObjCBridge#23]
This is right now just a producing a lot of compilation warnings, however, would be good to be prepared for ReactiveSwift 2.0

**Comment by andersio** [comment]
Sorry if it bothers you. This is a bit nasty for those who build directly from Xcode, but it should be silenced in Carthage and CocoaPods. Swift currently does not have measures to do only public deprecations, so we are stuck in the middle with it.

**Comment by andersio** [comment]
Fixed in 1.0.2.
