### ISSUE TITLE
Xcode 10 broken

### ISSUE THREAD

**Issue by AYastrebov** [ReactiveCocoa/ReactiveObjCBridge#52]
`extension Action {
    fileprivate var isEnabled: RACSignal<NSNumber> {
        return self.isEnabled.producer.map { $0 as NSNumber }.bridged
    }
}`

Gives error: ```Value of type 'RACSignal<NSNumber>' has no member 'producer'```

**Comment by mdiep** [comment]
Fixed by https://github.com/ReactiveCocoa/ReactiveObjCBridge/pull/51.
